spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/biblioteca}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate